version: '3.8'  # Specify the version of the Docker Compose file format

services:
  plotmanagement:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
